# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gem:                 [jekyll-paginate, jekyll-gists]

# Setup
title:               Sandbox
tagline:             'A Collection of Things'
description:         'A Collection of things I've found along the way.'
# url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Danning Ge
  url:               https://github.com/dannimals

# Custom vars
version:             1.0.0
