# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
gem:                 [jekyll-paginate, jekyll-gists]

# Setup
title:               Sandbox
tagline:             'A Collection of Things'
description:         A collection of things I've picked up along the way.
url:                 https://github.com/dannimals
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Danning Ge
  url:               http://github.com/dannimals

# Custom vars
version:             1.0.0
